// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "meta": string;
      "citekey": string;
      "tag_norecid": string;
      "tag_enable": boolean;
      "extra_order": string;
      "arxiv_tag_enable": boolean;
      "max_authors": number;
      "reader_auto_reopen": boolean;
      "chart_enable": boolean;
      "chart_default_collapsed": boolean;
      "latex_render_mode": string;
      "search_history_days": number;
      "pdf_fuzzy_citation": boolean;
      "pdf_parse_refs_list": boolean;
      "pdf_force_mapping_on_mismatch": boolean;
      "quick_filters_last_used": string;
      "local_cache_enable": boolean;
      "local_cache_ttl_hours": number;
      "local_cache_show_source": boolean;
      "local_cache_custom_dir": string;
      "local_cache_compression": boolean;
      "local_cache_enrich_batch": number;
      "local_cache_enrich_parallel": number;
      "smart_update_enable": boolean;
      "smart_update_show_preview": boolean;
      "smart_update_auto_check": boolean;
      "smart_update_protect_title": boolean;
      "smart_update_protect_authors": boolean;
      "smart_update_protect_abstract": boolean;
      "smart_update_protect_journal": boolean;
      "smart_update_protected_names": string;
      "preprint_watch_enabled": boolean;
      "preprint_watch_auto_check": string;
      "preprint_watch_last_check": number;
      "preprint_watch_notify": boolean;
      "collab_tag_enable": boolean;
      "collab_tag_auto": boolean;
      "collab_tag_template": string;
      "funding_china_only": boolean;
      "favorite_authors": string;
      "favorite_papers": string;
    };
  }
}
