// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "meta": string;
      "citekey": string;
      "tag_norecid": string;
      "tag_enable": boolean;
      "extra_order": string;
      "cites_column_exclude_self": boolean;
      "arxiv_in_journal_abbrev": boolean;
      "arxiv_tag_enable": boolean;
      "max_authors": number;
      "reader_auto_reopen": boolean;
      "chart_enable": boolean;
      "chart_default_collapsed": boolean;
      "related_papers_enable": boolean;
      "related_papers_exclude_reviews": boolean;
      "related_papers_max_results": number;
      "citation_graph_max_results": number;
      "citation_graph_include_reviews": boolean;
      "external_token": string;
      "latex_render_mode": string;
      "search_history_days": number;
      "pdf_fuzzy_citation": boolean;
      "pdf_parse_refs_list": boolean;
      "pdf_force_mapping_on_mismatch": boolean;
      "quick_filters_last_used": string;
      "ai_summary_enable": boolean;
      "ai_summary_provider": string;
      "ai_summary_preset": string;
      "ai_summary_base_url": string;
      "ai_summary_model": string;
      "ai_summary_temperature": number;
      "ai_summary_max_output_tokens": number;
      "ai_summary_output_mode": string;
      "ai_summary_output_language": string;
      "ai_summary_style": string;
      "ai_summary_citation_format": string;
      "ai_summary_include_seed_abstract": boolean;
      "ai_summary_include_abstracts": boolean;
      "ai_summary_max_refs": number;
      "ai_summary_abstract_char_limit": number;
      "ai_summary_cache_enable": boolean;
      "ai_summary_cache_ttl_hours": number;
      "ai_summary_streaming": boolean;
      "ai_summary_deep_read": boolean;
      "ai_summary_skip_references": boolean;
      "ai_batch_requests_per_minute": number;
      "ai_batch_max_items": number;
      "ai_profiles": string;
      "ai_active_profile_id": string;
      "ai_prompt_templates": string;
      "ai_deep_read_mode": string;
      "ai_library_qa_scope": string;
      "ai_library_qa_include_titles": boolean;
      "ai_library_qa_include_abstracts": boolean;
      "ai_library_qa_include_notes": boolean;
      "ai_library_qa_include_fulltext_snippets": boolean;
      "ai_library_qa_top_k": number;
      "ai_library_qa_snippets_per_item": number;
      "ai_library_qa_snippet_chars": number;
      "debug_panel_layout": boolean;
      "local_cache_enable": boolean;
      "local_cache_ttl_hours": number;
      "local_cache_show_source": boolean;
      "local_cache_custom_dir": string;
      "local_cache_compression": boolean;
      "local_cache_enrich_batch": number;
      "local_cache_enrich_parallel": number;
      "smart_update_enable": boolean;
      "smart_update_show_preview": boolean;
      "smart_update_auto_check": boolean;
      "smart_update_protect_title": boolean;
      "smart_update_protect_authors": boolean;
      "smart_update_protect_abstract": boolean;
      "smart_update_protect_journal": boolean;
      "smart_update_protected_names": string;
      "preprint_watch_enabled": boolean;
      "preprint_watch_auto_check": string;
      "preprint_watch_last_check": number;
      "preprint_watch_notify": boolean;
      "collab_tag_enable": boolean;
      "collab_tag_auto": boolean;
      "collab_tag_template": string;
      "funding_china_only": boolean;
      "favorite_authors": string;
      "favorite_papers": string;
      "favorite_presentations": string;
    };
  }
}
